// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd2COyIpYaOQ0ByYy3ETO5N-68Dw3hyq4',
    appId: '1:1074372818466:web:bf7942f9f2d54c90253c7b',
    messagingSenderId: '1074372818466',
    projectId: 'mygebeya-cffef',
    authDomain: 'mygebeya-cffef.firebaseapp.com',
    storageBucket: 'mygebeya-cffef.appspot.com',
    measurementId: 'G-YM3CYV101X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyRu8zbHDfSazEOPERm4zgwU5o3Y9eo4',
    appId: '1:1074372818466:android:1170e851b1d5f7dd253c7b',
    messagingSenderId: '1074372818466',
    projectId: 'mygebeya-cffef',
    storageBucket: 'mygebeya-cffef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjkgN-u87WyFRCyDEw5-bAMObHDysbLE',
    appId: '1:1074372818466:ios:996fb7557e38bc8c253c7b',
    messagingSenderId: '1074372818466',
    projectId: 'mygebeya-cffef',
    storageBucket: 'mygebeya-cffef.appspot.com',
    iosBundleId: 'com.example.mygebeya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjkgN-u87WyFRCyDEw5-bAMObHDysbLE',
    appId: '1:1074372818466:ios:72e4ac542880351b253c7b',
    messagingSenderId: '1074372818466',
    projectId: 'mygebeya-cffef',
    storageBucket: 'mygebeya-cffef.appspot.com',
    iosBundleId: 'com.example.mygebeya.RunnerTests',
  );
}
